### ISSUE TITLE
Feature: selecting the entrypoint

### ISSUE THREAD

**Issue by SirHerr** [PHT-Medic/central-ui#49]
### Reproduction

<details open>
<summary>When R is selected as programming language, python files can be selected. Vise versa identical.</summary>
</details>

### Steps to reproduce
Create a train

### What is Expected?
If python files are uploaded the user should only be able to select files with .py ( or R and .r)

### What is actually happening?
You can select any files as entrypoint. see screenshot:
<img width="1071" alt="Bildschirmfoto 2021-11-03 um 07 33 43" src="https://user-images.githubusercontent.com/10449223/140018375-101e0a3d-e9f6-4dc7-9d37-a886c062de23.png">

**Comment by tada5hi** [comment]
This will be ensured with the RMS.
