### ISSUE TITLE
Bug: Group master images

### ISSUE THREAD

**Issue by SirHerr** [PHT-Medic/central-ui#50]
### Reproduction

<details open>
<summary>Master image overview</summary>
</details>

### Steps to reproduce
When you submit a train, master images are listed by name but not grouped by programming language

### What is Expected?
You should see a grouped list by programming language

### What is actually happening?
You see a list of trains and cannot distinguish between base R or base Python master images.

**Comment by SirHerr** [comment]
See screenshot demonstrating the problem
<img width="979" alt="Bildschirmfoto 2021-11-03 um 07 32 12" src="https://user-images.githubusercontent.com/10449223/140018570-abfc83fb-f808-487d-a4aa-dca2f568dc26.png">

**Comment by Tada5hi** [comment]
This is already implemented, but not public live yet. See Screenshot: https://github.com/PHT-Medic/central-ui/issues/30#issuecomment-954007589
