### ISSUE TITLE
Feature: UUID mapping to human readable train ID

### ISSUE THREAD

**Issue by SirHerr** [PHT-Medic/central-ui#51]
### Problem
Train overview not human readable.

### Describe the solution you'd like

Please use an internal mapping of the train IDs to human readable 8 digit chars & numbers ID. Could be based on train proposals: e.g. CORD-0001, CORD-0002, ...

### Describe alternatives you've considered

make UUIDs shorter

### Additional context
Clarify how mapping of ID to PID will be securely communicated to station UI.

**Comment by Tada5hi** [comment]
Duplicate: https://github.com/PHT-Medic/central-ui/issues/42
